INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('Bougie végétale parfumée - 1 mèche coton - Verre 200ml', 'Bougie végétale parfumée. Superbe grande bougie végétale pour parfumer idéalement une grande pièce à vire. Bougie fraiche confectionnée à la commande', 'https://cdn.shopify.com/s/files/1/1406/4860/products/Bougie-parfumee-Bougies_5cd13dfb-7db2-491b-b38f-d64875489379_600x600.jpg', 22.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('Optimum Nutrition Gold Standard 100% Whey Protein Powder', 'Weight5 lbsFlavourDouble Rich ChocolateVegetarian/Non-VegetarianVegetarianNumber of Servings74Serving Size30.4gTotal Protein Per Container/Pouch', 'https://www.nutribuildup.com/images/detailed/6/Optimum_Nutrition__ON__Gold_Standard_100__Whey_Protein_Powder5_s0u7-xn.jpeg', 95.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('Tapis 120x170 cm SCANDI Gris', 'Décoration - Tapis - Paillasson - Tapis salon et chambre - Tapis 120x170 cm SCANDI Gris', 'https://image.but.fr/is/image/but/5415278653820_F?id=Jrwaw0&fmt=jpg&fit=constrain,1&wid=375&hei=533', 360.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('TV Samsung QE65Q80RATXXC QLED UHD 4K Smart TV Quantum Dot 65', 'Découvrez sans plus tarder le téléviseur Samsung QLED 65Q80R avec FNAC. Son écosystème Smart TV Samsung, sa qualité d’image époustouflante et son', 'https://static.fnac-static.com/multimedia/Images/FR/MDM/fe/77/ab/11237374/1540-1/tsp20191212151255/TV-Samsung-QE65Q80RATXXC-QLED-UHD-4K-Smart-TV-Quantum-Dot-65.jpg', 620.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('Nordace Siena - Smart Backpack - Nordace', 'Whether you’re hitting the trails, heading out for a day of shopping or spending the night at a silent retreat, our streamlined Siena Smart Backpack ', 'https://nordace.com/wp-content/uploads/2018/12/Nordace_Seina_Model_Smart_Backpack_12.jpg', 1200.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('Air Jordan XXXII Low', 'basketball shoe', 'https://cdn.runrepeat.com/i/jordan/26402/air-jordan-xxxii-low-white-white-white-0720-600.jpg', 180.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('ASUS ZenBook Pro Duo UX581GV XB74T - 15.6" - Core i7 9750H - 16 GB RAM - 1 TB SSD', 'The ZenBook Pro Duo''s full-width secondary ScreenPad Plus shows admirable commitment to innovation, but squeezing it into the chassis has consequences ',  'https://zdnet2.cbsistatic.com/hub/i/r/2019/09/23/7ab20904-1d60-474a-b2f8-6f364dbc0850/resize/1200x900/2c921ea82b6b475436bd528046e9309a/asus-zenbook-duo-header.jpg', 210.0);

INSERT INTO product (TITRE ,DESCRIPTION ,IMAGE ,PRIX ) VALUES ('Apple iPhone 11 Pro Max 64 Go Argent', 'Premier iPhone à décrocher l''appellation Pro, l''Apple iPhone Pro Max va vous en mettre plein les yeux. Avec sa finition exceptionnelle et son design ...', 'https://media.ldlc.com/r1600/ld/products/00/05/44/00/LD0005440078_2.jpg', 730.0);